version: '3.9'
services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 09po:L?>
      #restart: always
    networks:
      - sber-localhost
  back:
    image: newaldan/bugtracking-back
    container_name: bugtracking-back
    depends_on:
      - db
    restart: always
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
    networks:
      - sber-localhost
  front:
    image: newaldan/bugtracking-front
    container_name: bugtracking-front
    depends_on:
      - db
      - back
    ports:
      - "3000:3000"
    #restart: always
    stdin_open: true
    networks:
      - sber-localhost


networks:
  sber-localhost:
    driver: bridge
volumes:
  db-data: